### ISSUE TITLE
[UI] Titre = objet

### ISSUE THREAD

**Issue by ElodieTessier** [megalis-bretagne/MegActe#199]
**Capture d'écran**
<img width="427" alt="image" src="https://github.com/user-attachments/assets/813d0b17-70d1-45bf-b326-6654b74801c3">

**Description**
Il s'agit du 1er intitulé de la liste des documents

**Amélioration/Correction UI attendu**
Modifier le mot "Titre" en "Objet"

**Comment by syji35** [comment]
Corrigé @ElodieTessier 
![Image](https://github.com/user-attachments/assets/ceda8767-bd45-4395-ae13-d643870c9d5b)

**Comment by ElodieTessier** [comment]
Merci @syji35 !
