### ISSUE TITLE
[UI] Peut-on ajouter le numéro d'acte dans la liste des documents, juste avant l'objet.

### ISSUE THREAD

**Issue by ElodieTessier** [megalis-bretagne/MegActe#200]
**Capture d'écran**
<img width="589" alt="image" src="https://github.com/user-attachments/assets/7c964563-57f0-42dd-b0ec-db0d6d87bf40">

**Description**
Le numéro d'actes est important 

**Amélioration/Correction UI attendu**
ajouter le numéro d'acte dans la liste des documents, juste avant l'objet.

**Comment by syji35** [comment]
@ElodieTessier oui pas de problème.

je vais en profiter pour retirer la colonne "Type" lorsque l'utilisateur a déjà filtré sur un type de document (information redondante).

En revanche, il y a un cas particulier sur le le numéro d'acte et Titre. Lorsque le document est à l'état "création" (titre non renseigné), que dois afficher la colonne "Titre" ? 
Je propose d'afficher en italique "_Non renseigné_".

**Comment by syji35** [comment]
@ElodieTessier , en fait je suis limité par l'API de pastell.
Quand je récupère la liste des documents, je n'ai pas l'info du numéro de l'acte.
Je n'ai que le titre (objet) et son type. Il faudrait que je fasse autant de requête qu'il y a de document affiché pour avoir le numéro d'acte.
Ce qui n'est pas très eco responsable :D
