### ISSUE TITLE
[FEAT]AJouter d'autres type de documents

### ISSUE THREAD

**Issue by syji35** [megalis-bretagne/MegActe#213]
AJouter les documents suivants (flux) : 
- Doc budgétaire
- Acte réglémentaire
- Autres

**Comment by syji35** [comment]
Test avec ajout dans la conf des flux : budgetaire-studio, acte-reglementaire et autres-studio

**Comment by syji35** [comment]
Problème sur les flux budgétaire : il faut pouvoir gérer le fait que ca soit du XML et uniquement du XML.

Dans les flux, il est possible de renseigner le type de fichier (content-type) dans pastell.
Pour les flux budgétaire, il faut le renseigner a text/xml.
Ensuite, il faut prendre en compte cette valeur dans le formulaire de MegActes.
Par défaut, si pas de content-type renseigné, alors PDF.

**Comment by ElodieTessier** [comment]
OK @syji35  !
