### ISSUE TITLE
[UI] Dashboard MegActe

### ISSUE THREAD

**Issue by syji35** [megalis-bretagne/MegActe#35]
# Mise en place de la page d'accueil une fois connecter.

- [x] Mise en place d'un branchement keycloak
- [x] Migration vers Angular 17
- [x] Mise en place d'un composant Header
- [x] Mise en place du bouton "profil" de l'utilisateur

**Comment by syji35** [comment]
- [ ]  Le composant Header doit prendre toute la largeur de la page.
- [ ]  Ajouter un bouton "HOME" (avec le logo par exemple) qui renvoi vers la page d'accueil

**Comment by BoussairiIkram** [comment]
- [ ] Intégration du module DSFR. 
- [ ] Mise en place du processus de déconnexion. 
- [ ] Mise en place du processus de récupération et de visualisation infos user (Nom/Prénom/Entités..).
