### ISSUE TITLE
Nommage fichier PDF perdu dans le module Opendata"

### ISSUE THREAD

**Issue by MathieuConnan** [megalis-bretagne/MegActe#5]
Le nom des fichiers PDF est modifié dans le module opendata.
En effet, ils perdent leur nom de fichier et n'affiche que .pdf
![pdf_opendata](https://user-images.githubusercontent.com/111348275/186925538-90ebd8db-e368-4d52-bdb6-c1f21a4736af.png)

**Comment by ElodieTessier** [comment]
Juste pour ajouter que c'est uniquement au téléchargement du document.

**Comment by syji35** [comment]
Plus d'actualité
