### ISSUE TITLE
Suggestion organisation interface

### ISSUE THREAD

**Issue by ElodieTessier** [megalis-bretagne/MegActe#6]
C'est juste une suggestion, voici le visuel qui me semble être plus clair dans le process de publication :
<img width="960" alt="2022-09-02 16_51_56-Paramètres" src="https://user-images.githubusercontent.com/97222408/188177387-69dbf1f9-d1a8-4910-a175-11a5f0e51abc.png">

**Comment by VBD-CRB35** [comment]
Pour l'outil de gestion de publication open data : on est que sur la publication des actes non soumis ? dans ce cas le préciser

**Comment by spelhate** [comment]
> Pour l'outil de gestion de publication open data : on est que sur la publication des actes non soumis ? dans ce cas le préciser

L'outil de publication open data concerne tous les actes. En revanche le prototype M-Actes ne concerne lui que les documents non soumis au contrôle de légalité.

**Comment by syji35** [comment]
Revu sur la nouvlele version
