### ISSUE TITLE
[FEAT] Lister les documents dans un composant

### ISSUE THREAD

**Issue by syji35** [megalis-bretagne/MegActe#61]
## Cas d'usage
Lorsqu'un utilisateur est connecté, le dashboard affiche la liste des 10 derniers documents.

Le tableau contient : 
- le numéro de l'acte, 
- l'objet
- Le type d'acte
- la date
- Le dernier état

Ce tableau est filtrable en fonction du type d'acte sélectionné dans le dashboard de l'utilisateur (#53)

Ce tableau est paginé

Chaque ligne du tableau est cliquable pour voir le détail du document.

## API pastell

- Get /entite/id_e/document/
Il est possible de faire un appel paginé, avec les paramètre {"limit": 10, "offset": 0}

## Mapping dernier état
Suivant la valeur de "last_action_display" :  

| last_action_display | valeur à afficher |
| :--------------- |:--------------- | 
| termine  |   Traitement terminé  |
| accepter-sae | Archiver SAE |
| tdt-error | Erreur transmission tdt |
| recu-iparapheur |Transmis au parapheur |
| fatal-error] | Erreur inconnue |
| modification |En cours de rédaction |
| creation | En cours de rédaction  |

Si la valeur de "last_action_display " n'est pas présente dans le mapping, afficher la valeur tel quel.

**Comment by BoussairiIkram** [comment]
- PASTELL : Get /entite/id_e/document?type=tupe_flux :  Retourne les docs de type : "type_flux"

**Comment by syji35** [comment]
Le numéro d'acte ne sera pas affiché quand pas dispo dans l'API de la liste des entités.
Cela rejoint le problème de l'issue #66
