### ISSUE TITLE
[FEAT] Formulaire de création d'un type délibérations

### ISSUE THREAD

**Issue by syji35** [megalis-bretagne/MegActe#73]
### Cas d'usage
L'utilisateur peut enregistrer, transmettre un acte de type délibérations .

Lorsque l'utilisateur valide le formulaire via le bouton "enregistrer", le document est créé/mis à jours côté pastell.
(voir [figma](https://www.figma.com/proto/nFejN8tKQN6obIgpfTbU2P/Proto-Atelier-UX-Pastell-Utilisateurs?type=design&node-id=4045-298&t=N2h92Fn2VoJDXskj-0&scaling=min-zoom&page-id=0%3A1)):
 
Lorsque le document est complété, sans erreur, l'utilisateur peut cliquer sur le bouton enregistrer/transmettre le document.

Si la transmission n'est pas possible, un message d'erreur s'affiche avec le détail.

Pour le bouton de transmission : faire appel à l'API /entite/:id_e/document/:id_d/action/:action_name

**Comment by BoussairiIkram** [comment]
- Création de doc :  L'utilisateur peux modifier tt les champs.
- Doc envoyer : L'utilisateur peux visualiser le formulaire en mode lecture seul.
