### ISSUE TITLE
[UI] Amélioration de l'accessibilité

### ISSUE THREAD

**Issue by BoussairiIkram** [megalis-bretagne/MegActe#84]
**Description**
Suite à un test d'accessibilité, effectué par Florian, plusieurs améliorations ont été identifiées pour rendre l'interface utilisateur plus conviviale et accessible.

**Amélioration/Correction UI attendu**
- [ ] Augmenter la taille des icônes et de la police des éléments "Profil" et "Déconnexion" dans le header.
- [ ] Améliorer la navigation par tabulation pour éviter la perte de focus à l'arrivée sur l'ordre d'affichage.
- [ ] Ajouter un mode sombre pour l'application.
- [ ] Pour les champs de saisie avec calendrier, déplacer l'icône calendrier de la droite vers la gauche.

**Comment by syji35** [comment]
@FlorianChatel , je clos le ticket. L'UI a évolué depuis.

Pour chaque problème d'accessibilité, faire un ticket bien distinct
